CREATE TABLE IF NOT EXISTS llx_pvproc_raccordement
(
	rowid integer AUTO_INCREMENT PRIMARY KEY,
	entity integer DEFAULT 1 NOT NULL,
	ref varchar(128) NOT NULL,
	fk_soc integer,
	fk_project integer,
	fk_centrale_pv integer,
	site_source varchar(32) DEFAULT 'local',
	status integer DEFAULT 0 NOT NULL,
	type_exploitation varchar(64),
	puissance_installee_kwc double(24,8),
	puissance_injection_kva double(24,8),
	prm varchar(64),
	site_name_snapshot varchar(255),
	site_address_snapshot varchar(255),
	site_zip_snapshot varchar(20),
	site_town_snapshot varchar(128),
	type_reseau varchar(32),
	puissance_souscrite varchar(64),
	date_collecte_envoi datetime,
	date_collecte_ouverture datetime,
	date_collecte_soumission datetime,
	date_mandat_signature datetime,
	date_mandat_validation datetime,
	date_depot_enedis datetime,
	ref_enedis varchar(128),
	portail_utilise varchar(128),
	puissance_raccordement_demandee double(24,8),
	mono_tri_confirme varchar(32),
	onduleurs text,
	nombre_onduleurs integer,
	references_onduleurs text,
	puissance_onduleurs double(24,8),
	modules text,
	nombre_modules integer,
	puissance_unitaire_modules double(24,8),
	schema_unifilaire varchar(255),
	plan_masse varchar(255),
	plan_cadastral varchar(255),
	bilan_puissance varchar(255),
	consuel_requis integer DEFAULT 0,
	commentaire_technique text,
	demande_status integer DEFAULT 0,
	cardi_required integer DEFAULT 0,
	cardi_status integer DEFAULT 0,
	cardi_date_demande datetime,
	cardi_date_envoi_client datetime,
	cardi_date_retour_client datetime,
	cardi_date_validation datetime,
	cardi_document varchar(255),
	cardi_commentaire text,
	mes_required integer DEFAULT 0,
	mes_status integer DEFAULT 0,
	date_demande_mes datetime,
	date_previsionnelle_mes datetime,
	date_reelle_mes datetime,
	consuel_recu integer DEFAULT 0,
	date_consuel datetime,
	ref_consuel varchar(128),
	injection_autorisee integer DEFAULT 0,
	date_autorisation_injection datetime,
	ref_intervention_enedis varchar(128),
	commentaire_mes text,
	date_snapshot datetime,
	date_mes datetime,
	fk_user_author integer,
	fk_user_resp integer,
	fk_user_modif integer,
	note_private text,
	note_public text,
	datec datetime,
	tms timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	import_key varchar(14),
	UNIQUE KEY uk_pvproc_raccordement_ref_entity (entity, ref),
	KEY idx_pvproc_raccordement_entity (entity),
	KEY idx_pvproc_raccordement_ref (ref),
	KEY idx_pvproc_raccordement_fk_soc (fk_soc),
	KEY idx_pvproc_raccordement_fk_project (fk_project),
	KEY idx_pvproc_raccordement_fk_centrale_pv (fk_centrale_pv),
	KEY idx_pvproc_raccordement_status (status),
	KEY idx_pvproc_raccordement_date_depot_enedis (date_depot_enedis)
) ENGINE=innodb;
