<?php
/* Copyright (C) 2026 Pierre Ardoin <developpeur@lesmetiersdubatiment.fr>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 */

/**
 * Conservative adapter for optional Centrale PV integration.
 */
class CentralePVAdapter
{
	/**
	 * Database handler.
	 *
	 * @var DoliDB
	 */
	private $db;

	/**
	 * Detected module key.
	 *
	 * @var string
	 */
	private $moduleKey = '';

	/**
	 * Last error.
	 *
	 * @var string
	 */
	public $error = '';

	/**
	 * Constructor.
	 *
	 * @param DoliDB $db Database handler
	 */
	public function __construct($db)
	{
		$this->db = $db;
	}

	/**
	 * Return candidate module keys.
	 *
	 * @return list<string>
	 */
	private function getCandidateModuleKeys()
	{
		return array('powerplantpv', 'centralepv', 'centrale_pv', 'centralespv');
	}

	/**
	 * Detect optional module availability.
	 *
	 * @return bool
	 */
	public function isAvailable()
	{
		if (getDolGlobalInt('PROCEDURESPV_USE_CENTRALEPV_IF_AVAILABLE', 1) <= 0) {
			return false;
		}

		foreach ($this->getCandidateModuleKeys() as $moduleKey) {
			if (function_exists('isModEnabled') && isModEnabled($moduleKey)) {
				$this->moduleKey = $moduleKey;
				return true;
			}
		}

		return false;
	}

	/**
	 * Return main menu key to use when the module is detected.
	 *
	 * @return string
	 */
	public function getMainMenuKey()
	{
		if ($this->moduleKey === '') {
			$this->isAvailable();
		}

		return $this->moduleKey !== '' ? $this->moduleKey : 'procedurespv';
	}

	/**
	 * Fetch a Centrale PV-like row without assuming an external PHP class.
	 *
	 * @param int $id Centrale identifier
	 * @return stdClass|null
	 */
	public function fetchCentrale($id)
	{
		$id = (int) $id;
		if ($id <= 0 || !$this->isAvailable()) {
			return null;
		}

		foreach ($this->getCandidateTables() as $tableName) {
			if (!$this->tableExists($tableName)) {
				continue;
			}

			$sql = 'SELECT * FROM '.$tableName.' WHERE rowid = '.$id;
			$entityWhere = $this->getEntityWhereClause($tableName);
			if ($entityWhere !== '') {
				$sql .= ' AND '.$entityWhere;
			}
			$resql = $this->db->query($sql);
			if (!$resql) {
				$this->error = $this->db->lasterror();
				return null;
			}

			$obj = $this->db->fetch_object($resql);
			if (is_object($obj)) {
				return $obj;
			}
		}

		return null;
	}

	/**
	 * Return Centrale label.
	 *
	 * @param int $id Centrale identifier
	 * @return string
	 */
	public function getCentraleLabel($id)
	{
		$obj = $this->fetchCentrale($id);
		if (!is_object($obj)) {
			return '';
		}

		$label = $this->getCentraleLabelFromRow($obj);
		if ($label !== '') {
			return $label;
		}

		return (string) $id;
	}

	/**
	 * Return Centrale URL when a known route is available.
	 *
	 * @param int $id Centrale identifier
	 * @return string
	 */
	public function getCentraleUrl($id)
	{
		if (!$this->isAvailable()) {
			return '';
		}

		$moduleKey = $this->getMainMenuKey();
		$candidatePaths = array(
			'/'.$moduleKey.'/powerplant_card.php?id='.(int) $id,
			'/'.$moduleKey.'/centralepv_card.php?id='.(int) $id,
			'/'.$moduleKey.'/centrale/card.php?id='.(int) $id,
			'/'.$moduleKey.'/card.php?id='.(int) $id,
		);

		foreach ($candidatePaths as $path) {
			$localPath = dol_buildpath($path, 0);
			if ($localPath !== '' && file_exists($localPath)) {
				return dol_buildpath($path, 1);
			}
		}

		return '';
	}

	/**
	 * Return the native Centrale object when the optional module exposes it.
	 *
	 * @param int $id Centrale identifier
	 * @return CommonObject|null
	 */
	public function fetchCentraleNativeObject($id)
	{
		$id = (int) $id;
		if ($id <= 0 || !$this->isAvailable() || !function_exists('fetchObjectByElement')) {
			return null;
		}

		$elementTypesByModule = array(
			'powerplantpv' => array('powerplant@powerplantpv', 'powerplantpv_powerplant', 'powerplant'),
			'centralepv' => array('centralepv@centralepv', 'centralepv'),
			'centrale_pv' => array('centrale_pv@centrale_pv', 'centrale_pv'),
			'centralespv' => array('centralespv@centralespv', 'centralespv'),
		);
		$elementTypes = isset($elementTypesByModule[$this->moduleKey]) ? $elementTypesByModule[$this->moduleKey] : array();
		foreach ($elementTypes as $elementType) {
			$nativeObject = fetchObjectByElement($id, $elementType, '', 1);
			if (is_object($nativeObject) && method_exists($nativeObject, 'getNomUrl')) {
				return $nativeObject;
			}
		}

		return null;
	}

	/**
	 * Return the native Centrale link generated by its own object class.
	 *
	 * @param int $id Centrale identifier
	 * @param int $withpicto Include native picto
	 * @param string $option Native getNomUrl option
	 * @return string
	 */
	public function getCentraleNomUrl($id, $withpicto = 1, $option = '')
	{
		$nativeObject = $this->fetchCentraleNativeObject($id);
		if (!is_object($nativeObject) || !method_exists($nativeObject, 'getNomUrl')) {
			return '';
		}

		return (string) $nativeObject->getNomUrl((int) $withpicto, (string) $option);
	}

	/**
	 * Return selectable Centrale PV options.
	 *
	 * @param int $selectedId Selected centrale id
	 * @param int $limit Maximum number of options
	 * @return array<int,string>
	 */
	public function getCentraleOptions($selectedId = 0, $limit = 500)
	{
		$options = array();
		if (!$this->isAvailable()) {
			return $options;
		}

		foreach ($this->getCandidateTables() as $tableName) {
			if (!$this->tableExists($tableName)) {
				continue;
			}

			$sql = 'SELECT * FROM '.$tableName;
			$where = $this->getEntityWhereClause($tableName);
			if ($where !== '') {
				$sql .= ' WHERE '.$where;
			}
			$sql .= ' ORDER BY rowid DESC';
			if ($limit > 0) {
				$sql .= ' LIMIT '.((int) $limit);
			}

			$resql = $this->db->query($sql);
			if (!$resql) {
				$this->error = $this->db->lasterror();
				return $options;
			}

			while (is_object($obj = $this->db->fetch_object($resql))) {
				if (!isset($obj->rowid)) {
					continue;
				}
				$rowid = (int) $obj->rowid;
				if ($rowid <= 0) {
					continue;
				}

				$label = $this->getCentraleLabelFromRow($obj);
				$options[$rowid] = $label !== '' ? $label : (string) $rowid;
			}

			if (!empty($options)) {
				break;
			}
		}

		$selectedId = (int) $selectedId;
		if ($selectedId > 0 && empty($options[$selectedId])) {
			$obj = $this->fetchCentrale($selectedId);
			if (is_object($obj)) {
				$label = $this->getCentraleLabelFromRow($obj);
				$options[$selectedId] = $label !== '' ? $label : (string) $selectedId;
			}
		}

		return $options;
	}

	/**
	 * Return mapped site data.
	 *
	 * @param int $id Centrale identifier
	 * @return array<string, string|float|null>
	 */
	public function getSiteData($id)
	{
		$obj = $this->fetchCentrale($id);
		if (!is_object($obj)) {
			return array();
		}

		return array(
			'site_name' => $this->readFirstString($obj, array('label', 'nom', 'name', 'ref')),
			'address' => $this->readFirstString($obj, array('address', 'site_address', 'adresse')),
			'zip' => $this->readFirstString($obj, array('zip', 'site_zip', 'cp', 'code_postal')),
			'town' => $this->readFirstString($obj, array('town', 'site_town', 'ville')),
			'prm' => $this->readFirstString($obj, array('prm', 'pdl', 'prm_pdl', 'prm_pdl_number')),
			'puissance_installee_kwc' => $this->readFirstFloat($obj, array('puissance_installee_kwc', 'installed_power', 'power_kwc', 'puissance')),
			'puissance_injection_kva' => $this->readFirstFloat($obj, array('puissance_injection_kva', 'connection_contract_power', 'injection_kva', 'puissance_injection')),
			'type_exploitation' => $this->readFirstString($obj, array('type_exploitation', 'exploitation_type', 'connection_type')),
			'type_pose' => $this->readFirstString($obj, array('type_pose', 'pose_type')),
		);
	}

	/**
	 * Return the site values provided by the Centrale selected as source.
	 *
	 * Empty source values are omitted so they never erase data already
	 * collected on the grid connection during a prefill operation.
	 *
	 * @param Raccordement $raccordement Grid connection
	 * @return array{site_name?:string,address?:string,zip?:string,town?:string,prm?:string}
	 */
	public function getRaccordementSourceSiteData($raccordement)
	{
		if (
			!is_object($raccordement)
			|| (string) $raccordement->site_source !== 'centralepv'
			|| (int) $raccordement->fk_centrale_pv <= 0
			|| getDolGlobalInt('PROCEDURESPV_PREFILL_FROM_CENTRALEPV', 1) <= 0
		) {
			return array();
		}

		$siteData = $this->getSiteData((int) $raccordement->fk_centrale_pv);
		$result = array();
		foreach (array('site_name', 'address', 'zip', 'town', 'prm') as $key) {
			if (!array_key_exists($key, $siteData) || $siteData[$key] === null) {
				continue;
			}
			$value = trim((string) $siteData[$key]);
			if ($value !== '') {
				$result[$key] = $value;
			}
		}

		return $result;
	}

	/**
	 * Prefill the grid-connection snapshot from its Centrale source.
	 *
	 * @param Raccordement $raccordement Grid connection to update in memory
	 * @return list<string> Changed Raccordement field names
	 */
	public function prefillRaccordementSiteData($raccordement)
	{
		$siteData = $this->getRaccordementSourceSiteData($raccordement);
		$fieldMap = array(
			'site_name_snapshot' => 'site_name',
			'site_address_snapshot' => 'address',
			'site_zip_snapshot' => 'zip',
			'site_town_snapshot' => 'town',
			'prm' => 'prm',
		);
		$changedFields = array();
		foreach ($fieldMap as $targetField => $sourceField) {
			if (!isset($siteData[$sourceField])) {
				continue;
			}
			$value = (string) $siteData[$sourceField];
			if ((string) $raccordement->{$targetField} === $value) {
				continue;
			}
			$raccordement->{$targetField} = $value;
			$changedFields[] = $targetField;
		}

		return $changedFields;
	}

	/**
	 * Synchronize mandate site corrections back to the native Centrale object.
	 *
	 * @param int $id Centrale identifier
	 * @param array{site_name:string,address:string,zip:string,town:string,prm:string} $siteData Submitted site data
	 * @param User $user Acting workflow user
	 * @return int 1 on success, -1 on error
	 */
	public function updateSiteData($id, array $siteData, $user)
	{
		$this->error = '';
		$id = (int) $id;
		if ($id <= 0 || !is_object($user) || !is_object($this->fetchCentrale($id))) {
			$this->error = 'CentralePVSiteSynchronizationFailed';
			return -1;
		}

		$nativeObject = $this->fetchCentraleNativeObject($id);
		if (!is_object($nativeObject) || !method_exists($nativeObject, 'update')) {
			$this->error = 'CentralePVSiteSynchronizationFailed';
			dol_syslog(__METHOD__.' native Centrale object unavailable for id '.$id, LOG_ERR);
			return -1;
		}

		$propertyCandidates = array(
			'site_name' => array('label', 'nom', 'name'),
			'address' => array('address', 'site_address', 'adresse'),
			'zip' => array('zip', 'site_zip', 'cp', 'code_postal'),
			'town' => array('town', 'site_town', 'ville'),
			'prm' => array('prm_pdl_number', 'prm_pdl', 'prm', 'pdl'),
		);
		$oldcopy = clone $nativeObject;
		$nativeFields = isset($nativeObject->fields) && is_array($nativeObject->fields) ? $nativeObject->fields : array();
		$changedProperties = array();
		foreach ($propertyCandidates as $sourceField => $candidates) {
			$value = array_key_exists($sourceField, $siteData) ? trim((string) $siteData[$sourceField]) : '';
			$targetProperty = '';
			foreach ($candidates as $candidate) {
				if (property_exists($nativeObject, $candidate) || array_key_exists($candidate, $nativeFields)) {
					$targetProperty = $candidate;
					break;
				}
			}
			if ($targetProperty === '' || (string) $nativeObject->{$targetProperty} === $value) {
				continue;
			}
			$nativeObject->{$targetProperty} = $value;
			$changedProperties[] = $targetProperty;
		}

		if (empty($changedProperties)) {
			return 1;
		}

		$nativeObject->oldcopy = $oldcopy;
		if (!isset($nativeObject->context) || !is_array($nativeObject->context)) {
			$nativeObject->context = array();
		}
		$nativeObject->context['trigger_reason'] = 'procedurespv_mandate_site_sync';
		$nativeObject->context['changed_fields'] = $changedProperties;
		$result = $nativeObject->update($user);
		if (!is_int($result) || $result <= 0) {
			$nativeError = isset($nativeObject->error) ? trim((string) $nativeObject->error) : '';
			dol_syslog(__METHOD__.' failed for Centrale id '.$id.($nativeError !== '' ? ': '.$nativeError : ''), LOG_ERR);
			$this->error = 'CentralePVSiteSynchronizationFailed';
			return -1;
		}

		return 1;
	}

	/**
	 * Return candidate table names.
	 *
	 * @return list<string>
	 */
	private function getCandidateTables()
	{
		return array(
			MAIN_DB_PREFIX.'powerplantpv_powerplant',
			MAIN_DB_PREFIX.'centralepv_centrale',
			MAIN_DB_PREFIX.'centrale_pv_centrale',
			MAIN_DB_PREFIX.'centralespv_centrale',
			MAIN_DB_PREFIX.'centralepv',
		);
	}

	/**
	 * Return display label from a fetched Centrale PV row.
	 *
	 * @param stdClass $obj Source object
	 * @return string
	 */
	private function getCentraleLabelFromRow($obj)
	{
		$parts = array();
		foreach (array('ref', 'label', 'nom', 'name') as $field) {
			if (isset($obj->{$field}) && trim((string) $obj->{$field}) !== '') {
				$parts[] = trim((string) $obj->{$field});
			}
		}

		return implode(' - ', array_unique($parts));
	}

	/**
	 * Return SQL entity filter for a known optional Centrale PV table.
	 *
	 * @param string $tableName Full table name
	 * @return string
	 */
	private function getEntityWhereClause($tableName)
	{
		global $conf;

		if (!$this->tableHasColumn($tableName, 'entity')) {
			return '';
		}

		if (function_exists('getEntity')) {
			$entityList = (string) getEntity($this->getEntityElementForTable($tableName));
			if ($entityList !== '') {
				return 'entity IN ('.$entityList.')';
			}
		}

		$entity = (is_object($conf) && !empty($conf->entity)) ? (int) $conf->entity : 1;
		return 'entity = '.$entity;
	}

	/**
	 * Return Multicompany element key for a candidate table.
	 *
	 * @param string $tableName Full table name
	 * @return string
	 */
	private function getEntityElementForTable($tableName)
	{
		if (strpos($tableName, 'powerplantpv_powerplant') !== false) {
			return 'powerplant';
		}
		if (strpos($tableName, 'centrale_pv') !== false) {
			return 'centrale_pv';
		}
		if (strpos($tableName, 'centralespv') !== false) {
			return 'centralespv';
		}

		return 'centralepv';
	}

	/**
	 * Check table existence.
	 *
	 * @param string $tableName Full table name
	 * @return bool
	 */
	private function tableExists($tableName)
	{
		$sql = "SHOW TABLES LIKE '".$this->db->escape($tableName)."'";
		$resql = $this->db->query($sql);

		return $resql && $this->db->num_rows($resql) > 0;
	}

	/**
	 * Check column existence.
	 *
	 * @param string $tableName Full table name
	 * @param string $columnName Column name
	 * @return bool
	 */
	private function tableHasColumn($tableName, $columnName)
	{
		$sql = 'SHOW COLUMNS FROM '.$this->db->sanitize($tableName)." LIKE '".$this->db->escape($columnName)."'";
		$resql = $this->db->query($sql);

		return $resql && $this->db->num_rows($resql) > 0;
	}

	/**
	 * Read first non-empty string field from an object.
	 *
	 * @param stdClass $obj Source object
	 * @param list<string> $fields Field names
	 * @return string|null
	 */
	private function readFirstString($obj, array $fields)
	{
		foreach ($fields as $field) {
			if (isset($obj->{$field}) && trim((string) $obj->{$field}) !== '') {
				return (string) $obj->{$field};
			}
		}

		return null;
	}

	/**
	 * Read first numeric field from an object.
	 *
	 * @param stdClass $obj Source object
	 * @param list<string> $fields Field names
	 * @return float|null
	 */
	private function readFirstFloat($obj, array $fields)
	{
		foreach ($fields as $field) {
			if (isset($obj->{$field}) && is_numeric($obj->{$field})) {
				return (float) $obj->{$field};
			}
		}

		return null;
	}
}
